import type { Metadata } from "../../node_modules/next/types";
import { FiltersFinanceProvider } from "./(protected)/finances/context/financeContext";

import "./globals.css";

export const metadata: Metadata = {
  title: "IverNet",
  description: "Generated by ...",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body>
        <FiltersFinanceProvider>{children}</FiltersFinanceProvider>
      </body>
    </html>
  );
}
