import type { Metadata } from "../../node_modules/next/types";
import "./globals.css";

export const metadata: Metadata = {
  title: "IverNet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}